name: memoir_reader
description: An AI based application software that allows users to listen to memoirs, blogs, articles etc, and export to mp3

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 
  curved_navigation_bar: ^1.0.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  bot_toast: ^4.0.1
  lottie: ^1.2.1
  flutter_dialogs: ^2.1.0
  nanoid: ^1.0.0 
  pull_to_refresh: ^2.0.0
  flutter_form_builder: ^6.1.0+1
  super_tooltip: ^1.0.1
  font_awesome_flutter: ^10.2.1
  avatar_glow: ^2.0.2
  flutter_tts: ^3.5.3
  sliding_up_panel: ^2.0.0+1
  expandable_bottom_sheet: ^1.1.1+1
  url_launcher: ^6.1.6
  provider: ^6.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_native_splash:
  tuple: ^2.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  uuid: ^3.0.6


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # 
  
  flutter_launcher_icons: ^0.10.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.2
  json_serializable: ^6.1.5

  # 
  # flutter_form_builder: ^6.1.0+1
  # flutter_spinkit: ^5.1.0
  # pinput: ^1.2.0
  # flutter_swiper: ^1.1.6
  # line_icons: ^2.0.1
  # community_material_icon: ^5.9.55
  # logging: ^1.0.1
  # we_slide: ^2.2.1
  # sliding_up_panel: ^2.0.0+1
  # dotted_border: ^2.0.0+1
  # flutter_rating_bar: ^4.0.0
  # super_tooltip: ^1.0.1
  # simple_tooltip: ^1.0.0
  # regexed_validator: ^2.0.0+1
  # flutter_countdown_timer: ^4.1.0
  # firebase_core: ^1.8.0
  # path_provider: ^2.0.5
  # image_picker: ^0.8.4+3
  # cached_network_image: ^3.1.0
  # dio_smart_retry: ^1.1.0
  # pull_to_refresh: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mrIcon.png"

flutter_native_splash:
  color: "#2DF27C"
  image: assets/icon/mrIcon.png
  color_dark: "#000000"
  image_dark: assets/icon/mrIconLabelW.png


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar/
    - assets/anim/
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
